[tool.poetry]
name = "noted"
version = "0.1.0"
description = "A Markdown-base note-taking program"
authors = ["David Eidelman <eidelman.david@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
Flask = "^2.2.2"

[tool.poetry.dev-dependencies]
mypy = "^0.982"
black = "^22.8.0"
pytest = "^7.1.3"
pylint = "^2.15.3"
SQLAlchemy = "^1.4.41"
pydantic = "^1.10.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
